CREATE TABLE categories (
    id SERIAL PRIMARY KEY,
	user_id INT,
    name VARCHAR(100) NOT NULL,
	type VARCHAR(10) NOT NULL CHECK (type IN ('entrada', 'saida')),
    status BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);